force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/E2E_Symphony_Billing_Admin_Preferences__c.object-meta.xml
<CustomObject>
    <description>Includes elements for the Broker to complete the billing &amp; payment preferences, as well as Admin preferences, for the client after an insurance plan is selected for the E2E Symphony Reimagine POC</description>
    <label>Billing &amp; Admin Preferences</label>
    <nameField>
        <displayFormat>BAP-{00000}</displayFormat>
        <label>Billing &amp; Admin Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing &amp; Admin Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Account__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing &amp; Admin Preferences</relationshipLabel>
    <relationshipName>E2E_Symphony_Billing_Admin_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Account_Number__c</fullName>
    <description>account number for payment method</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Admin_Fee_Basis__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Admin_Fee_Basis__c</fullName>
    <label>Admin Fee Basis</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PCPM or PMPM enrollment w/ discount sharing as % of savings</fullName>
                <label>PCPM / PMPM enrollment w/ discount sharing as % of savings</label>
            </value>
            <value>
                <fullName>Per claim or as % of claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Bank_Name__c</fullName>
    <description>The Bank Name for the payment method</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Bank Name</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Bill_Delivery__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Bill_Delivery__c</fullName>
    <label>Bill Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronic Bill</fullName>
            </value>
            <value>
                <fullName>Electronic Bill and Standard Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Number_of_Bills__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Number_of_Bills__c</fullName>
    <description>The number of bills the client will receive</description>
    <label>Number of Bills</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Bill</fullName>
            </value>
            <value>
                <fullName>Separate Bills</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Payment_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Payment_Account_Type__c</fullName>
    <description>The payment method account type</description>
    <label>Payment Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Payment_preference__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Payment_preference__c</fullName>
    <description>The payment preference</description>
    <label>Payment preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Payments</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Routing_Number__c</fullName>
    <description>Routing number for Bank information</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Self_Billing__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Self_Billing__c</fullName>
    <label>Self Billing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No - Recommended</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Billing_Admin_Preferences__c/fields/E2E_Symphony_Waiting_Period__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Waiting_Period__c</fullName>
    <label>Waiting Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 3 Days, Net 5 and 7 -Recommended</fullName>
            </value>
            <value>
                <fullName>Net Days: 1,2,4,8,9,10,11,12,13,14</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APISymphonyGroupBillPref.cls
/*
 * Symphony Group Bill Pref API
 * 
 * PUT /group/billpref/{billPrefId}
 * GET /group/billpref?groupId={groupId}
 * 
 */
@RestResource(urlMapping='/symphony/group/billpref/*')
global with sharing class APISymphonyGroupBillPref {

    @HttpPut
    global static SymphonyGroupBillPref updateGroupBillPref(SymphonyGroupBillPref symphonyGroupBillPref) {
        String id = RestContext.request.requestURI.substring(RestContext.request.requestURI.lastIndexOf('/') + 1);

        E2E_Symphony_Billing_Admin_Preferences__c billingAdminPreferences = symphonyGroupBillPref.toBillingAdminPreferences();
        billingAdminPreferences.Id = id;
        update billingAdminPreferences;

        return new SymphonyGroupBillPref(billingAdminPreferences);
    }

    @HttpGet
    global static SymphonyGroupBillPref getGroupBillPref() {
        String groupId = RestContext.request.params.get('groupId');

        SymphonyGroupBillPref symphonyGroupBillPref;

        if (String.isNotBlank(groupId)) {
			List<E2E_Symphony_Billing_Admin_Preferences__c> billingAdminPreferencesList = [
                SELECT
                	E2E_Symphony_Account__c, E2E_Symphony_Account_Number__c, E2E_Symphony_Admin_Fee_Basis__c,
                	E2E_Symphony_Bank_Name__c, E2E_Symphony_Bill_Delivery__c, E2E_Symphony_Number_of_Bills__c,
					E2E_Symphony_Payment_Account_Type__c, E2E_Symphony_Payment_preference__c,
                	E2E_Symphony_Routing_Number__c, E2E_Symphony_Self_Billing__c, E2E_Symphony_Waiting_Period__c
                FROM
                	E2E_Symphony_Billing_Admin_Preferences__c
                WHERE
                	E2E_Symphony_Account__c = :groupId
                LIMIT 1
            ];
            
            if (billingAdminPreferencesList.size() > 0) {
                return new SymphonyGroupBillPref(billingAdminPreferencesList[0]);
            } else {
                // No record found.
        		RestContext.response.statusCode = 404;
            }
        } else {
        	// Invalid request.
        	RestContext.response.statusCode = 400;
        }

        return symphonyGroupBillPref;
    }


    global class SymphonyGroupBillPref {

        global String id {get; set;}
        global String groupId {get; set;}
        global String accountNumber {get; set;}
        global String adminFeeBasis {get; set;}
        global String bankName {get; set;}
        global String billDelivery {get; set;}
        global String numberOfBills {get; set;}
        global String paymentAccountType {get; set;}
        global String paymentpreference {get; set;}
        global String routingNumber {get; set;}
        global String selfBilling {get; set;}
        global String waitingPeriod {get; set;}


        global SymphonyGroupBillPref() {
        }

        global SymphonyGroupBillPref(E2E_Symphony_Billing_Admin_Preferences__c billingAdminPreferences) {
            id = billingAdminPreferences.Id;
            groupId = billingAdminPreferences.E2E_Symphony_Account__c;
            accountNumber = billingAdminPreferences.E2E_Symphony_Account_Number__c;
            adminFeeBasis = billingAdminPreferences.E2E_Symphony_Admin_Fee_Basis__c;
            bankName = billingAdminPreferences.E2E_Symphony_Bank_Name__c;
            billDelivery = billingAdminPreferences.E2E_Symphony_Bill_Delivery__c;
            numberOfBills = billingAdminPreferences.E2E_Symphony_Number_of_Bills__c;
            paymentAccountType = billingAdminPreferences.E2E_Symphony_Payment_Account_Type__c;
            paymentpreference = billingAdminPreferences.E2E_Symphony_Payment_preference__c;
            routingNumber = billingAdminPreferences.E2E_Symphony_Routing_Number__c;
            selfBilling = billingAdminPreferences.E2E_Symphony_Self_Billing__c;
            waitingPeriod = billingAdminPreferences.E2E_Symphony_Waiting_Period__c;
        }

        public E2E_Symphony_Billing_Admin_Preferences__c toBillingAdminPreferences() {
            E2E_Symphony_Billing_Admin_Preferences__c billingAdminPreferences = new E2E_Symphony_Billing_Admin_Preferences__c();
            billingAdminPreferences.Id = id;
            billingAdminPreferences.E2E_Symphony_Account__c = groupId;
            billingAdminPreferences.E2E_Symphony_Account_Number__c = accountNumber;
            billingAdminPreferences.E2E_Symphony_Admin_Fee_Basis__c = adminFeeBasis;
            billingAdminPreferences.E2E_Symphony_Bank_Name__c = bankName;
            billingAdminPreferences.E2E_Symphony_Bill_Delivery__c = billDelivery;
            billingAdminPreferences.E2E_Symphony_Number_of_Bills__c = numberOfBills;
            billingAdminPreferences.E2E_Symphony_Payment_Account_Type__c = paymentAccountType;
            billingAdminPreferences.E2E_Symphony_Payment_preference__c = paymentpreference;
            billingAdminPreferences.E2E_Symphony_Routing_Number__c = routingNumber;
            billingAdminPreferences.E2E_Symphony_Self_Billing__c = selfBilling;
            billingAdminPreferences.E2E_Symphony_Waiting_Period__c = waitingPeriod;

            return billingAdminPreferences;
        }

    }
    
}