force-app/main/default/objects/Census_Member_Reimagine_POC__c/Census_Member_Reimagine_POC__c.object-meta.xml
<CustomObject>
    <description>This is used in the Reimagine POC and houses the information that comes in from the census data at the member level.</description>
    <label>Group Roster</label>
    <nameField>
        <displayFormat>CMN-{00000000}</displayFormat>
        <label>Census Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Rosters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/Birthday_Text__c.field-meta.xml
<CustomField>
    <fullName>Birthday_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Birthday Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/Census__c.field-meta.xml
<CustomField>
    <fullName>Census__c</fullName>
    <description>Used to connect the census member data to the census in the reimagine POC</description>
    <label>Census</label>
    <referenceTo>Census_Reimagine_POC__c</referenceTo>
    <relationshipName>Census_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/eligibility__c.field-meta.xml
<CustomField>
    <fullName>eligibility__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>eligibility</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>firstName</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Used to house the census member&#39;s gender.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>lastName</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Member_Reimagine_POC__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/symphonyCreateRosterData.cls
@RestResource(urlMapping='/symphony/tempRoster/*')

global with sharing class symphonyCreateRosterData {
    @HttpPost
    global static void parseData(SymphonyRoster symphonyRoster) {
        List<Census_Member_Reimagine_POC__c> bulkUpdate = new List<Census_Member_Reimagine_POC__c>();

        for(RosterPeople rp : symphonyRoster.rosterPeople) {
            Census_Member_Reimagine_POC__c censusMember = new Census_Member_Reimagine_POC__c();
            censusMember.Census__c = 'a9O19000000Fk2aEAC';
            censusMember.firstName__c = rp.firstName;
            censusMember.lastName__c = rp.lastName;
            censusMember.Birthday_Text__c = rp.dateOfBirth;
            censusMember.Zip_Code__c = rp.zip;
            censusMember.Gender__c = rp.sex;
            censusMember.Tier__c = rp.tier;
            censusMember.eligibility__c = rp.eligibility;
            bulkUpdate.add(censusMember);
        }
        insert bulkUpdate;

    }

    global class SymphonyRoster {
        public List<RosterPeople> rosterPeople {get; set;}
    }

    global class RosterPeople {
        public String firstName {get; set;}
        public String lastName {get; set;}
        public String dateOfBirth {get; set;}
        public String zip {get; set;}
        public String sex {get; set;}
        public String tier {get; set;}
        public String eligibility {get; set;}
    }
}