force-app/main/default/objects/Quote/fields/Sym_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Sym_Completed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Symphony_Status__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Status__c</fullName>
    <description>Used in the symphony POC and stores the pizza tracker status.</description>
    <label>Symphony Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Profile</fullName>
            </value>
            <value>
                <fullName>Get Recommendation</fullName>
            </value>
            <value>
                <fullName>Get Rate</fullName>
            </value>
            <value>
                <fullName>Plan Selection</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Customer Setup</fullName>
            </value>
            <value>
                <fullName>Access to Care</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Soldcase_Symphony__c/Soldcase_Symphony__c.object-meta.xml
<CustomObject>
    <label>Soldcase</label>
    <nameField>
        <displayFormat>SC-{00000000}</displayFormat>
        <label>Soldcase Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soldcases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Soldcases</relationshipLabel>
    <relationshipName>Soldcases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Sold_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Sold_Case_Status__c</fullName>
    <label>Sold Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Sent to Employer</fullName>
            </value>
            <value>
                <fullName>Signed by Employer</fullName>
            </value>
            <value>
                <fullName>Signed by Broker</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APISymphonyProposal.cls
/*
 * Symphony Proposal API
 * 
 * POST /proposal/
 * PUT /proposal/
 *
 */
@RestResource(urlMapping='/symphony/proposal/*')
global with sharing class APISymphonyProposal {
    global class ReturnState {
        public String symphonyStatus;
        public ReturnState(String theState) {
            this.symphonyStatus = theState;
        }
    }
    @HttpPost
    global static ReturnState createProposal(SymphonyProposal symphonyProposal) {
        Quote quote = [SELECT Id, Symphony_Status__c FROM Quote WHERE Id = :symphonyProposal.salesForceQuoteId];
        quote.Symphony_Status__c = 'Proposal';
        quote.Sym_Completed_Date__c = Date.parse(symphonyProposal.selectedPlans.completedDate);
        List<QuoteLineItem> quoteLineItems = [SELECT Id, ProductStage__c, Product2.Name, Product2.Contract_Code__c FROM QuoteLineItem WHERE QuoteId = :symphonyProposal.salesForceQuoteId];
        //Create a set to hold the selected plan contract IDs and then populate it
        Set<String> contractIdsOfSelectedPlans = new Set<String>();
        for(SelectedPlansList spl: symphonyProposal.selectedPlans.selectedPlanList) {
            contractIdsOfSelectedPlans.add(spl.contractID);
        }
        //Loop through the quote line items and determine if the line item was a selected plan       
        for(QuoteLineItem qli: quoteLineItems) {
            if(contractIdsOfSelectedPlans.contains(qli.Product2.Contract_Code__c)) {
                qli.ProductStage__c = 'Sold';
            } else {
                qli.ProductStage__c = 'Lost';
            }
        }
        try {
            update quoteLineItems;
            update quote;
        } catch(DmlException e)  {
            //returnMessage = e.getMessage();
        } 

        return new ReturnState(quote.Symphony_Status__c);
    }

    @HttpPut
    global static ReturnState updateProposal(SymphonyProposalUpdate symphonyProposalUpdate) {
        Soldcase_Symphony__c soldcase = [SELECT Id, Sold_Case_Status__c 
        FROM Soldcase_Symphony__c
        WHERE Quote__c = :symphonyProposalUpdate.quoteId];

        soldcase.Sold_Case_Status__c = symphonyProposalUpdate.status;
        update soldcase;

        return new ReturnState(soldcase.Sold_Case_Status__c);

    }

    global class SymphonyProposal {
        public SelectedPlans selectedPlans {get; set;}
        public String salesForceQuoteId {get; set;}
    }

    public class SelectedPlans {
        public List<SelectedPlansList> selectedPlanList {get; set;}
        public String completedDate {get; set;}
    }

    public class SelectedPlansList {
        public String contractID {get; set;}
    }

    global class SymphonyProposalUpdate {
        public String quoteId {get; set;}
        public String status {get; set;}
    }

}