force-app/main/default/objects/Quote/fields/Symphony_Status__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Status__c</fullName>
    <description>Used in the symphony POC and stores the pizza tracker status.</description>
    <label>Symphony Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Profile</fullName>
            </value>
            <value>
                <fullName>Get Recommendation</fullName>
            </value>
            <value>
                <fullName>Get Rate</fullName>
            </value>
            <value>
                <fullName>Plan Selection</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Customer Setup</fullName>
            </value>
            <value>
                <fullName>Access to Care</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/rate_eeChildren__c.field-meta.xml
<CustomField>
    <fullName>rate_eeChildren__c</fullName>
    <label>rate_eeChildren</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/rate_family__c.field-meta.xml
<CustomField>
    <fullName>rate_family__c</fullName>
    <label>rate_family</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/rate_single_number__c.field-meta.xml
<CustomField>
    <fullName>rate_single_number__c</fullName>
    <label>rate_single_number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/rate_twoParty__c.field-meta.xml
<CustomField>
    <fullName>rate_twoParty__c</fullName>
    <label>rate_twoParty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Symphony_Rating_Return__e/Symphony_Rating_Return__e.object-meta.xml
<CustomObject>
    <label>Symphony Rating Return</label>
    <pluralLabel>Symphony Rating Returns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Symphony_Rating_Return__e/fields/payload__c.field-meta.xml
<CustomField>
    <fullName>payload__c</fullName>
    <description>Handles the JSON payload coming in from the rating engine.</description>
    <label>payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SymphonyTriggerHandler.cls
public with sharing class SymphonyTriggerHandler {
    public SymphonyTriggerHandler() {

    }


    public static void SymphonyRatingReturn(List<Symphony_Rating_Return__e> symphonyRatingReturns ) {
        for(Symphony_Rating_Return__e srr : symphonyRatingReturns) {
            AnthemAPI.RatingResponse rr = (AnthemAPI.RatingResponse) JSON.deserialize(EncodingUtil.base64Decode(srr.payload__c).toString(), AnthemAPI.RatingResponse.class);
            Quote quote = [SELECT Id FROM Quote WHERE Id = :rr.quoteHeaderID];
            quote.Symphony_Status__c = 'Plan Selection';
            update quote;
            
            Set<Id> qliIDs = new Set<Id>();

            for(AnthemAPI.RatingInfo ri : rr.rateInfo) {
                qliIDs.add(ri.quoteLineItemID);
            }
            
            Map<Id, QuoteLineItem> qliMap = new Map<Id, QuoteLineItem>([SELECT Id FROM QuoteLineItem WHERE Id IN : qliIDs]);

            for (AnthemAPI.RatingInfo ri : rr.rateInfo) {
                QuoteLineItem qli = qliMap.get(ri.quoteLineItemID);
                qli.UnitPrice = ri.single;
                qli.rate_single_number__c = ri.single;
                qli.rate_eeChildren__c = ri.eeChildren;
                qli.rate_family__c = ri.family;
                qli.rate_twoParty__c = ri.twoParty;
                qli.sym_monthlyPremium__c = ri.monthlyPremium;
            }
            update qliMap.values();
        }
    }
}