force-app/main/default/objects/Soldcase_Symphony__c/Soldcase_Symphony__c.object-meta.xml
<CustomObject>
    <label>Soldcase</label>
    <nameField>
        <displayFormat>SC-{00000000}</displayFormat>
        <label>Soldcase Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soldcases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Soldcases</relationshipLabel>
    <relationshipName>Soldcases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Signed_Broker_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Broker_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signed Broker Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Signed_Broker_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Signed_Broker_FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signed Broker FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Signed_Broker_LastName__c.field-meta.xml
<CustomField>
    <fullName>Signed_Broker_LastName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Signed Broker LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Soldcase_Symphony__c/fields/Sold_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Sold_Case_Status__c</fullName>
    <label>Sold Case Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Sent to Employer</fullName>
            </value>
            <value>
                <fullName>Signed by Employer</fullName>
            </value>
            <value>
                <fullName>Signed by Broker</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APISymphonyBrokerSign.cls
/*
 * Symphony Proposal API
 * 
 * POST /brokerSign
 * 
 */
 @RestResource(urlMapping='/symphony/brokerSign/*')
global with sharing class APISymphonyBrokerSign {
    global class ReturnState {
        public String symphonyStatus;
        public ReturnState(String theState) {
            this.symphonyStatus = theState;
        }
    }

    @HttpPost
    global static ReturnState employerSign(SymphonyEmployerSign symphonyEmployerSign) {
        Soldcase_Symphony__c soldCase = [SELECT Id FROM Soldcase_Symphony__c
        WHERE Quote__c = :symphonyEmployerSign.salesForceQuoteId
        LIMIT 1];

        soldCase.Signed_Broker_FirstName__c = symphonyEmployerSign.firstName;
        soldCase.Signed_Broker_LastName__c = symphonyEmployerSign.lastName;
        soldCase.Signed_Broker_Date__c = Date.parse(symphonyEmployerSign.dateSigned);
        soldCase.Sold_Case_Status__c = 'Signed by Broker';
        update soldCase;

        return new ReturnState(soldCase.Sold_Case_Status__c);
    }

    global class SymphonyEmployerSign {
        public String firstName {get; set;}
        public String lastName {get; set;}
        public String dateSigned {get; set;}
        public String salesForceQuoteId {get; set;}
    }
}