force-app/main/default/objects/Product2/fields/E2E_Symphony_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Coinsurance__c</fullName>
    <description>E2E Symphony field for POC - Coinsurance is an attribute of a plan</description>
    <label>Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Coinsurance_Pharmacy__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Coinsurance_Pharmacy__c</fullName>
    <description>E2E Symphony field for POC - Coinsurance is an attribute of a plan</description>
    <label>Coinsurance (Pharmacy Included)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Deductible__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Deductible__c</fullName>
    <description>E2E Symphony field for POC - Deductible field is an attribute of a plan</description>
    <label>Individual Deductible In-Network</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Maximum_Out_of_Pocket__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Maximum_Out_of_Pocket__c</fullName>
    <description>E2E Symphony field for POC - Maximum Out of Pocket is an attribute of a plan</description>
    <label>Maximum Out of Pocket</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Preventative_Drugs_Covered__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Preventative_Drugs_Covered__c</fullName>
    <description>E2E Symphony field for POC - Preventative Drugs Covered is an attribute of a plan</description>
    <label>Preventative Drugs Covered (Pharmacy)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Primary_Care_Copay__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Primary_Care_Copay__c</fullName>
    <description>E2E Symphony field for POC - Primary Care Copay field is an attribute of a plan</description>
    <label>Primary Care Copay</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Rx_network__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Rx_network__c</fullName>
    <description>E2E Symphony field for POC - Rx Network is an attribute of a plan</description>
    <label>Rx Network</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rx Choice Tiered with R90</fullName>
            </value>
            <value>
                <fullName>OH-LG-RX Ded/20%/30% Tiered</fullName>
            </value>
            <value>
                <fullName>OH-LG-RX Ded/0%/10% Tiered</fullName>
            </value>
            <value>
                <fullName>OH-LG-RX T6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Specialist_Copay__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Specialist_Copay__c</fullName>
    <description>E2E Symphony field for POC - Specialist Copay is an attribute of a plan</description>
    <label>Specialist Copay</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Sympony_Rx_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sympony_Rx_Plan__c</fullName>
    <description>E2E Symphony field for POC - Rx Plan is an attribute of a plan</description>
    <label>Rx Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4-Tier</fullName>
            </value>
            <value>
                <fullName>3-Tier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/symphony_Temp_Rate__c.field-meta.xml
<CustomField>
    <fullName>symphony_Temp_Rate__c</fullName>
    <description>This is temporary to hold the rate for demo purposes.</description>
    <label>Temp Rate</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Symphony_Status__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Status__c</fullName>
    <description>Used in the symphony POC and stores the pizza tracker status.</description>
    <label>Symphony Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Profile</fullName>
            </value>
            <value>
                <fullName>Get Recommendation</fullName>
            </value>
            <value>
                <fullName>Get Rate</fullName>
            </value>
            <value>
                <fullName>Plan Selection</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Customer Setup</fullName>
            </value>
            <value>
                <fullName>Access to Care</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/symphonyGetQuoteAndLineItems.cls
public with sharing class symphonyGetQuoteAndLineItems {
    @AuraEnabled(cacheable=false)
    public static Quote getLineItems(Id recordId) {
        Quote theQuote = [SELECT Id, (SELECT Id, UnitPrice, ProductStage__c, sym_IsSold__c, Product2.Name, Product2.E2E_Symphony_Coinsurance__c,Product2.E2E_Symphony_Deductible__c,Product2.E2E_Symphony_Primary_Care_Copay__c,Contract_Codes__c,
                                             Product2.E2E_Symphony_Specialist_Copay__c,Product2.E2E_Symphony_Maximum_Out_of_Pocket__c, Product2.E2E_Symphony_Rx_network__c, Product2.E2E_Sympony_Rx_Plan__c,
                                             Product2.E2E_Symphony_Coinsurance_Pharmacy__c, Product2.E2E_Symphony_Preventative_Drugs_Covered__c, Product2.symphony_Temp_Rate__c FROM QuoteLineItems) FROM Quote WHERE Id = :recordId];
        return theQuote;
    }

    @AuraEnabled
    public static String updateQuoteLineItems(Id quoteId, Id selectedLineItem) {
        String returnMessage = 'Success';
        Quote theQuote = [SELECT Id, Symphony_Status__c FROM Quote WHERE Id = :quoteId];
        theQuote.Symphony_Status__c = 'Proposal';
        List<QuoteLineItem> theLineItems = [SELECT Id, ProductStage__c, Product2.Name FROM QuoteLineItem WHERE QuoteId = :quoteId];
        List<QuoteLineItem> modifiedLineItems = new List<QuoteLineItem>();
        for(QuoteLineItem aLineItem: theLineItems) {
            if(aLineItem.Id == selectedLineItem) {
                if(aLineItem.ProductStage__c == 'Sold') {
                    aLineItem.ProductStage__c = 'Lost';
                    returnMessage += ': ' + aLineItem.Product2.Name + ' is no longer a selected plan.';    
                } else {
                    aLineItem.ProductStage__c = 'Sold';
                    returnMessage += ': ' + aLineItem.Product2.Name + ' is now a selected plan.';
                }
                modifiedLineItems.add(aLineItem);                
            } /*else {
                aLineItem.ProductStage__c = 'Lost';
            } */
        }
        try {
            update modifiedLineItems;
            update theQuote;
        } catch(DmlException e)  {
            returnMessage = e.getMessage();
        } 
        return returnMessage;
    }
}