force-app/main/default/objects/Product2/fields/E2E_Symphony_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Coinsurance__c</fullName>
    <description>E2E Symphony field for POC - Coinsurance is an attribute of a plan</description>
    <label>Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Coinsurance_Pharmacy__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Coinsurance_Pharmacy__c</fullName>
    <description>E2E Symphony field for POC - Coinsurance is an attribute of a plan</description>
    <label>Coinsurance (Pharmacy Included)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Deductible__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Deductible__c</fullName>
    <description>E2E Symphony field for POC - Deductible field is an attribute of a plan</description>
    <label>Individual Deductible In-Network</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_DEDUCTIBLE_FAMILY__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_DEDUCTIBLE_FAMILY__c</fullName>
    <label>Deductible - Family</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_EMERGENCY_ROOM_CO_PAY__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_EMERGENCY_ROOM_CO_PAY__c</fullName>
    <label>Emergency Room -  Co Pay</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_IN_PATIENT_HOSP_COIN__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_IN_PATIENT_HOSP_COIN__c</fullName>
    <label>In Patient Hospital - Co Insurance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Maximum_Out_of_Pocket__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Maximum_Out_of_Pocket__c</fullName>
    <description>E2E Symphony field for POC - Maximum Out of Pocket is an attribute of a plan</description>
    <label>Maximum Out of Pocket</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_MAXIMUM_OUT_OF_POCKET_FAMIL__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_MAXIMUM_OUT_OF_POCKET_FAMIL__c</fullName>
    <label>Maximum Out of Pocket - Family</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_OFF_VISIT_EPHC_COPAY__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_OFF_VISIT_EPHC_COPAY__c</fullName>
    <label>Office Visit EPHC - Co Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_OFF_VISIT_PCP_COPAY__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_OFF_VISIT_PCP_COPAY__c</fullName>
    <label>Office Visit PCP - Co Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_OFF_VISIT_SCP_COPAY__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_OFF_VISIT_SCP_COPAY__c</fullName>
    <label>Office Visit SCP - Co Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Pharmacy_Included__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pharmacy Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Preventative_Drugs_Covered__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Preventative_Drugs_Covered__c</fullName>
    <description>E2E Symphony field for POC - Preventative Drugs Covered is an attribute of a plan</description>
    <label>Preventative Drugs Covered (Pharmacy)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Primary_Care_Copay__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Primary_Care_Copay__c</fullName>
    <description>E2E Symphony field for POC - Primary Care Copay field is an attribute of a plan</description>
    <label>Primary Care Copay</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Rx_network__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Rx_network__c</fullName>
    <description>E2E Symphony field for POC - Rx Network is an attribute of a plan</description>
    <label>Rx Network</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rx Choice Tiered with R90</fullName>
            </value>
            <value>
                <fullName>OH-LG-RX Ded/20%/30% Tiered</fullName>
            </value>
            <value>
                <fullName>OH-LG-RX Ded/0%/10% Tiered</fullName>
            </value>
            <value>
                <fullName>OH-LG-RX T6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Symphony_Specialist_Copay__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Specialist_Copay__c</fullName>
    <description>E2E Symphony field for POC - Specialist Copay is an attribute of a plan</description>
    <label>Specialist Copay</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_SYMPHONY_URGENT_CARE_CO_PAY__c.field-meta.xml
<CustomField>
    <fullName>E2E_SYMPHONY_URGENT_CARE_CO_PAY__c</fullName>
    <label>Urgent Care - Co Pay</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/E2E_Sympony_Rx_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sympony_Rx_Plan__c</fullName>
    <description>E2E Symphony field for POC - Rx Plan is an attribute of a plan</description>
    <label>Rx Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4-Tier</fullName>
            </value>
            <value>
                <fullName>3-Tier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/E2E_Symphony_Recommendation_Order__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Recommendation_Order__c</fullName>
    <description>This is used to hold the order the recommended plans come back in, this is required as the order needs to be kept on the API return,</description>
    <label>Recommendation Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/E2E_Symphony_Recommendation_Type__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Recommendation_Type__c</fullName>
    <description>This is used to hold what type of plan was returned from the recommendation API. Values are popular or recommended.</description>
    <label>Recommendation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Popular</fullName>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APISymphonyPlan.cls
/*
 * Symphony Plan API
 * 
 * GET /plans?quoteId={quoteId}
 * 
 */
@RestResource(urlMapping='/symphony/plans/*')
global with sharing class APISymphonyPlan {

    @HttpGet
    global static GetPlansResponse getPlans() {
        String quoteId = RestContext.request.params.get('quoteId');

        GetPlansResponse getPlansResponse = new GetPlansResponse();

        if (String.isNotBlank(quoteId)) {
			List<QuoteLineItem> quoteLineItems = [
                SELECT
                	QuoteId, E2E_Symphony_Recommendation_Type__c, Product2.Name, Product2.ProductCode,
                    Product2.Contract_Code__c, Product2.Plan_Name__c, UnitPrice,
                    Product2.E2E_Symphony_Deductible__c, Product2.E2E_Symphony_Primary_Care_Copay__c,
                    Product2.E2E_Symphony_Specialist_Copay__c, Product2.E2E_Symphony_Maximum_Out_of_Pocket__c,
                	Product2.E2E_Symphony_Coinsurance__c, Product2.E2E_Symphony_Pharmacy_Included__c,
                	Product2.E2E_Symphony_Rx_network__c, Product2.E2E_Symphony_Coinsurance_Pharmacy__c,
                	Product2.E2E_Sympony_Rx_Plan__c, Product2.E2E_Symphony_Preventative_Drugs_Covered__c,

					Product2.E2E_Symphony_Deductible_Family__c, Product2.E2E_Symphony_Maximum_Out_Of_Pocket_Famil__c,
					Product2.E2E_Symphony_Emergency_Room_Co_Pay__c, Product2.E2E_Symphony_Off_Visit_Ephc_Copay__c,
					Product2.E2E_Symphony_Off_Visit_PCP_Copay__c, Product2.E2E_Symphony_Off_Visit_SCP_Copay__c,
					Product2.E2E_Symphony_In_Patient_Hosp_Coin__c, Product2.E2E_Symphony_Urgent_Care_Co_Pay__c
                FROM
                	QuoteLineItem
                WHERE
                	QuoteId = :quoteId
                ORDER BY
                	E2E_Symphony_Recommendation_Order__c ASC
            ];

            for (QuoteLineItem quoteLineItem : quoteLineItems) {
                if (quoteLineItem.E2E_Symphony_Recommendation_Type__c == 'Popular') {
                    getPlansResponse.popularPlans.add(new SymphonyPlan(quoteLineItem));
                } else if (quoteLineItem.E2E_Symphony_Recommendation_Type__c == 'Recommended') {
                    getPlansResponse.recommendedPlans.add(new SymphonyPlan(quoteLineItem));
                }
            }
        } else {
        	// Invalid request.
        	RestContext.response.statusCode = 400;
        }

        return getPlansResponse;
    }

	global class GetPlansResponse {

        global List<SymphonyPlan> popularPlans {get; set;}
        global List<SymphonyPlan> recommendedPlans {get; set;}

        
        global GetPlansResponse() {
            popularPlans = new List<SymphonyPlan>();
            recommendedPlans = new List<SymphonyPlan>();
        }

    }
    
    global class SymphonyPlan {

        global String id {get; set;}
        global String quoteId {get; set;}
        global String productId {get; set;}
        global String productName {get; set;}
        global Integer coinsurance {get; set;}
        global Integer coinsurancePharmacy {get; set;}
        global String contractCode {get; set;}
        global Decimal deductible {get; set;}
        global Integer deductibleFamily {get; set;}
        global Integer emergencyRoomCopay {get; set;}
        global Integer inPatient {get; set;}
        global Integer maximumOutOfPocket {get; set;}
        global Integer maximumOutOfPocketFamily {get; set;}
        global Integer offVisitEPHCCopay {get; set;}
        global Integer offVisitPCPCopay {get; set;}
        global Integer offVisitSCPCopay {get; set;}
        global Boolean pharmacyIncluded {get; set;}
        global String planName {get; set;}
        global String preventativeDrugsCovered {get; set;}
        global Integer primaryCareCopay {get; set;}
        global String rxNetwork {get; set;}
        global String rxPlan {get; set;}
        global Integer specialistCopay {get; set;}
        global Decimal unitPrice {get; set;}
        global Integer urgentCareCopay {get; set;}


		global SymphonyPlan() {
		}

        global SymphonyPlan(QuoteLineItem quoteLineItem) {
            id = quoteLineItem.Id;
            quoteId = quoteLineItem.QuoteId;
            productId = quoteLineItem.Product2.ProductCode;
            productName = quoteLineItem.Product2.Name;
            coinsurance = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Coinsurance__c);
            coinsurancePharmacy = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Coinsurance_Pharmacy__c);
            contractCode = quoteLineItem.Product2.Contract_Code__c;
            deductible = quoteLineItem.Product2.E2E_Symphony_Deductible__c;
            deductibleFamily = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Deductible_Family__c);
            emergencyRoomCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Emergency_Room_Co_Pay__c);
            inPatient = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_In_Patient_Hosp_Coin__c);
            maximumOutOfPocket = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Maximum_Out_of_Pocket__c);
            maximumOutOfPocketFamily = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Maximum_Out_Of_Pocket_Famil__c);
            offVisitEPHCCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Off_Visit_Ephc_Copay__c);
            offVisitPCPCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Off_Visit_PCP_Copay__c);
            offVisitSCPCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Off_Visit_SCP_Copay__c);
            pharmacyIncluded = quoteLineItem.Product2.E2E_Symphony_Pharmacy_Included__c;
            planName = quoteLineItem.Product2.Plan_Name__c;
			preventativeDrugsCovered = quoteLineItem.Product2.E2E_Symphony_Preventative_Drugs_Covered__c;
            primaryCareCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Primary_Care_Copay__c);
            rxNetwork = quoteLineItem.Product2.E2E_Symphony_Rx_network__c;
            rxPlan = quoteLineItem.Product2.E2E_Sympony_Rx_Plan__c;
            specialistCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Specialist_Copay__c);
            unitPrice = quoteLineItem.UnitPrice;
            urgentCareCopay = APISymphonyRecPlans.integerValue(quoteLineItem.Product2.E2E_Symphony_Urgent_Care_Co_Pay__c);
        }

    }
    
}