force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>Used in the Symphony POC and will hold the account&#39;s county.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <description>This is used for the Symphony POC and matches the pick list on the broker portal.</description>
    <label>Number of Employees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>51-99</fullName>
            </value>
            <value>
                <fullName>100-249</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Symphony_Account.recordType-meta.xml
<RecordType>
    <fullName>Symphony_Account</fullName>
    <active>true</active>
    <description>This is being used for the POC to account for Large Group Prospects where data required is minimized.</description>
    <label>Symphony Account</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Symphony_Contact.recordType-meta.xml
<RecordType>
    <fullName>Symphony_Contact</fullName>
    <active>true</active>
    <description>Used for the Symphony POC and requires very few fields.</description>
    <label>Symphony Contact</label>
</RecordType>

force-app/main/default/classes/symphonyCreateAccount.cls
@RestResource(urlMapping='/symphony/createAccountContact/*')
global with sharing class symphonyCreateAccount {
    @HttpPost
    //Replace hard coded record types
    //Tries around the inserts
    global static void doPost(String name, String sic, String street, String city, String postalCode, String county, String total_Employees,
                             String firstName, String lastName, String phone, String email) { 
	    Id symphonyAccount = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Symphony_Account').getRecordTypeId();
    	Id symphonyContact = SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Symphony_Contact').getRecordTypeId();
        Account newAccount = new Account(
            Name=name, RecordTypeId=symphonyAccount,Number_of_Employees__c=total_Employees, SIC=sic, County__c=county, BillingPostalCode=postalCode, BillingStreet=street
        );
    	insert newAccount;
        Contact newContact = new Contact(
        	AccountId=newAccount.Id, FirstName=firstName, LastName=lastName, Email=email, Phone=phone, RecordTypeId=symphonyContact
        );
        insert newContact;
    }
}