force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>Used in the Symphony POC and will hold the account&#39;s county.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <description>This is used for the Symphony POC and matches the pick list on the broker portal.</description>
    <label>Number of Employees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>51-99</fullName>
            </value>
            <value>
                <fullName>100-249</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Symphony_Account.recordType-meta.xml
<RecordType>
    <fullName>Symphony_Account</fullName>
    <active>true</active>
    <description>This is being used for the POC to account for Large Group Prospects where data required is minimized.</description>
    <label>Symphony Account</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Symphony_Contact.recordType-meta.xml
<RecordType>
    <fullName>Symphony_Contact</fullName>
    <active>true</active>
    <description>Used for the Symphony POC and requires very few fields.</description>
    <label>Symphony Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Symphony_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Symphony_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Symphony Sales</businessProcess>
    <description>Used for the Symphony POC.</description>
    <label>Symphony Opportunity</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Symphony_Status__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Status__c</fullName>
    <description>Used in the symphony POC and stores the pizza tracker status.</description>
    <label>Symphony Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Profile</fullName>
            </value>
            <value>
                <fullName>Get Recommendation</fullName>
            </value>
            <value>
                <fullName>Get Rate</fullName>
            </value>
            <value>
                <fullName>Plan Selection</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Customer Setup</fullName>
            </value>
            <value>
                <fullName>Access to Care</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Symphony_Quote.recordType-meta.xml
<RecordType>
    <fullName>Symphony_Quote</fullName>
    <active>true</active>
    <description>Used for the Symphony POC</description>
    <label>Symphony Quote</label>
</RecordType>

force-app/main/default/classes/symphonyPortalDataIn.cls
@RestResource(urlMapping='/symphonyNotPublished/*')
global with sharing class symphonyPortalDataIn {
    @HttpPost
    //Replace hard coded record types
    //Tries around the inserts
    global static void doPost(String name, String sic, String street, String city, String postalCode, String county, String total_Employees,
                             String firstName, String lastName, String phone, String email) { 
	    Id symphonyAccount = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Symphony_Account').getRecordTypeId();
    	Id symphonyContact = SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Symphony_Contact').getRecordTypeId();
		Id symphonyOpportunity = SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Symphony_Opportunity').getRecordTypeId();
		Id symphonyQuote = SObjectType.Quote.getRecordTypeInfosByDeveloperName().get('Symphony_Quote').getRecordTypeId();
		//For the demo we are hard coding the broker to me.
        Contact theBroker = [SELECT Id, Name FROM Contact WHERE Id = '0031900000Y7VgIAAV'];
        Account newAccount = new Account(
            Name=name, RecordTypeId=symphonyAccount,Number_of_Employees__c=total_Employees, SIC=sic, County__c=county, BillingPostalCode=postalCode, BillingStreet=street
        );
    	insert newAccount;
        Contact newContact = new Contact(
        	AccountId=newAccount.Id, FirstName=firstName, LastName=lastName, Email=email, Phone=phone, RecordTypeId=symphonyContact
        );
        insert newContact;

    	Opportunity newOpportunity = new Opportunity(
        	Name=String.valueOf(Date.Today().year()) + ' New Business-' + name, AccountId=newAccount.Id,CloseDate=Date.Today()+30,StageName='Initiated', RecordTypeId=symphonyOpportunity
    	);
    	insert newOpportunity;
        
        Quote newQuote = new Quote(
        	ContactId=theBroker.Id, RecordTypeId=symphonyQuote,Name=String.valueOf(Date.Today().year()) + ' New Business-' + name, OpportunityId=newOpportunity.Id,
            vlocity_ins__EffectiveDate__c=Date.Today()+90, Symphony_Status__c='Group Profile'
        );
		insert newQuote;
        
    }
}