force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>Used in the Symphony POC and will hold the account&#39;s county.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/Census_Reimagine_POC__c.object-meta.xml
<CustomObject>
    <description>Contains information for the E2E Reimagine POC related to Group (Account) demographic data known as &quot;census&quot;.  This data can change periodically as the group profile changes</description>
    <label>Census</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Census</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Census</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Active_Member_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Member_Count__c</fullName>
    <label>Active Member Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Employee_with_dependents__c.field-meta.xml
<CustomField>
    <fullName>Employee_with_dependents__c</fullName>
    <label>Employee with dependents</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/employeeChildrenPMPM__c.field-meta.xml
<CustomField>
    <fullName>employeeChildrenPMPM__c</fullName>
    <label>Employee Children PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/employeeSpousePMPM__c.field-meta.xml
<CustomField>
    <fullName>employeeSpousePMPM__c</fullName>
    <label>Employee Spouse PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/familyPMPM__c.field-meta.xml
<CustomField>
    <fullName>familyPMPM__c</fullName>
    <label>Family PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/indvidualPMPM__c.field-meta.xml
<CustomField>
    <fullName>indvidualPMPM__c</fullName>
    <label>Individual PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_below_20__c.field-meta.xml
<CustomField>
    <fullName>Number_below_20__c</fullName>
    <label>Number below 20</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_Between_21_30__c.field-meta.xml
<CustomField>
    <fullName>Number_Between_21_30__c</fullName>
    <label>Number Between 21-30</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_between_31_40__c.field-meta.xml
<CustomField>
    <fullName>Number_between_31_40__c</fullName>
    <label>Number between 31-40</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_between_41_50__c.field-meta.xml
<CustomField>
    <fullName>Number_between_41_50__c</fullName>
    <label>Number between 41-50</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_between_51_60__c.field-meta.xml
<CustomField>
    <fullName>Number_between_51_60__c</fullName>
    <label>Number between 51-60</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_Employee_Spouse__c.field-meta.xml
<CustomField>
    <fullName>Number_Employee_Spouse__c</fullName>
    <label>Number Employee + Spouse</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_family_plans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_family_plans__c</fullName>
    <label>Number of family plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_Female__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Female__c</fullName>
    <label>Number of Female</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_individual_plans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_individual_plans__c</fullName>
    <label>Number of individual plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_Male__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Male__c</fullName>
    <label>Number of Male</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_Plans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Plans__c</fullName>
    <label>Number of Plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_over_60__c.field-meta.xml
<CustomField>
    <fullName>Number_over_60__c</fullName>
    <label>Number over 60</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/E2E_Symphony_Fine_Tune_Recommendation__c.object-meta.xml
<CustomObject>
    <label>Fine Tune Recommendations</label>
    <nameField>
        <displayFormat>FTR-{00000}</displayFormat>
        <label>Fine Tune Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fine Tune Recommendations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Fam_Out_Network_Deductible_Max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Fam_Out_Network_Deductible_Max__c</fullName>
    <label>Family deductible out of network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Family_In_Network_Deductible_Max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Family_In_Network_Deductible_Max__c</fullName>
    <label>Family deductible in network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Account__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fine Tune Recommendations</relationshipLabel>
    <relationshipName>Fine_Tune_Recommendations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_HMO_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_HMO_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HMO Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_HSA_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_HSA_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HSA Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_POS_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_POS_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POS Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_PPO_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_PPO_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PPO Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/Prior_EOB_Symphony__c.object-meta.xml
<CustomObject>
    <description>Summary of Benefits</description>
    <label>SOB</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Prior EOB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SOBs</relationshipLabel>
    <relationshipName>SOBs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Coinsurance_INN__c.field-meta.xml
<CustomField>
    <fullName>Current_Coinsurance_INN__c</fullName>
    <label>Current Coinsurance INN</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Coinsurance_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_Coinsurance_OON__c</fullName>
    <label>Current Coinsurance OON</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Family_Deductible_In_Network__c.field-meta.xml
<CustomField>
    <fullName>Current_Family_Deductible_In_Network__c</fullName>
    <label>Current Family Deductible In Network</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Family_Deductible_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_Family_Deductible_OON__c</fullName>
    <label>Current Family Deductible OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Individual_Deductible_In_Network__c.field-meta.xml
<CustomField>
    <fullName>Current_Individual_Deductible_In_Network__c</fullName>
    <label>Current Individual Deductible In Network</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Individual_Deductible_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_Individual_Deductible_OON__c</fullName>
    <label>Current Individual Deductible OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Family_INN__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Family_INN__c</fullName>
    <label>Current OOP max Family INN</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Family_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Family_OON__c</fullName>
    <label>Current OOP max Family OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Individual_INN__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Individual_INN__c</fullName>
    <label>Current OOP max Individual INN</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Individual_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Individual_OON__c</fullName>
    <label>Current OOP max Individual OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Four_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Four_Coinsurance__c</fullName>
    <label>Current Rx Tier Four Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Four_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Four_Copay__c</fullName>
    <label>Current Rx Tier Four Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_One_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_One_Coinsurance__c</fullName>
    <label>Current Rx Tier One Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_One_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_One_Copay__c</fullName>
    <label>Current Rx Tier One Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Three_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Three_Coinsurance__c</fullName>
    <label>Current Rx Tier Three Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Three_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Three_Copay__c</fullName>
    <label>Current Rx Tier Three Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Two_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Two_Coinsurance__c</fullName>
    <label>Current Rx Tier Two Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Two_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Two_Copay__c</fullName>
    <label>Current Rx Tier Two Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/symphonyCoLo3EndPoint.cls
/*
 * Symphony Find Plans API
 * 
 * PUT /plan/{accountId}
 * 
 */

//@RestResource(urlMapping='/symphony/tempfindPlans/*')
public with sharing class symphonyCoLo3EndPoint {   
    //@HttpPut
    public static void findPlans(AnthemAPI.RecommendationRequest recommendationRequest, Id accountId) {
        //String id = RestContext.request.requestURI.substring(RestContext.request.requestURI.lastIndexOf('/') + 1);
        String id = accountId;

        Account currentAccount = [SELECT Id
        FROM Account
        WHERE id = :id 
        LIMIT 1];
        E2E_Symphony_Fine_Tune_Recommendation__c fineTuneRecord = [SELECT Id 
        FROM E2E_Symphony_Fine_Tune_Recommendation__c
        WHERE E2E_Symphony_Account__c = :id
        LIMIT 1];
        Census_Reimagine_POC__c censusRecord = [Select Id 
        FROM Census_Reimagine_POC__c
        WHERE Account__c = :id
        LIMIT 1];
        Prior_EOB_Symphony__c sobRecord = [Select Id
        FROM Prior_EOB_Symphony__c
        WHERE Account__c = :id
        LIMIT 1];

        censusRecord.Active_Member_Count__c	 = recommendationRequest.activeMemberCount;
        currentAccount.county__c = recommendationRequest.county;
        sobRecord.Current_Coinsurance_INN__c = recommendationRequest.currentCoinsuranceINN * 100;
        sobRecord.Current_Coinsurance_OON__c = recommendationRequest.currentCoinsuranceOON * 100;
        sobRecord.Current_Family_Deductible_In_Network__c = recommendationRequest.currentFamilyDeductibleINN;
        sobRecord.Current_Family_Deductible_OON__c = recommendationRequest.currentFamilyDeductibleOON;
        sobRecord.Current_Individual_Deductible_In_Network__c = recommendationRequest.currentIndividualDeductibleINN;
        sobRecord.Current_Individual_Deductible_OON__c = recommendationRequest.currentIndividualDeductibleOON;
        sobRecord.Current_OOP_max_Family_INN__c = recommendationRequest.currentOOPmaxFamilyINN;
        sobRecord.Current_OOP_max_Family_OON__c = recommendationRequest.currentOOPmaxFamilyOON;
        sobRecord.Current_OOP_max_Individual_INN__c = recommendationRequest.currentOOPmaxIndividualINN;
        sobRecord.Current_OOP_max_Individual_OON__c = recommendationRequest.currentOOPmaxIndividualOON;
        sobRecord.Current_Rx_Tier_Four_Coinsurance__c = recommendationRequest.currentRxTierFourCoinsurance;
        sobRecord.Current_Rx_Tier_Four_Copay__c = recommendationRequest.currentRxTierFourCopay;
        sobRecord.Current_Rx_Tier_One_Coinsurance__c = recommendationRequest.currentRxTierOneCoinsurance;
        sobRecord.Current_Rx_Tier_One_Copay__c = recommendationRequest.currentRxTierOneCopay;
        sobRecord.Current_Rx_Tier_Three_Coinsurance__c = recommendationRequest.currentRxTierThreeCoinsurance;
        sobRecord.Current_Rx_Tier_Three_Copay__c = recommendationRequest.currentRxTierThreeCopay;
        sobRecord.Current_Rx_Tier_Two_Coinsurance__c = recommendationRequest.currentRxTierTwoCoinsurance;
        sobRecord.Current_Rx_Tier_Two_Copay__c = recommendationRequest.currentRxTierTwoCopay;

        //recommendationRequest.effectiveDt;
        censusRecord.employeeChildrenPMPM__c = recommendationRequest.employeeChildrenPMPM;
        censusRecord.employeeSpousePMPM__c = recommendationRequest.employeeSpousePMPM;
        censusRecord.familyPMPM__c = recommendationRequest.familyPMPM;
        censusRecord.indvidualPMPM__c = recommendationRequest.indvidualPMPM;

        //Need to beef up when multiple are passed along
        switch on recommendationRequest.memberSelectionCategory {
            when 'HMO' {		// when block 1
                fineTuneRecord.E2E_Symphony_HMO_Medical_Plan__c = true;
            }	
            when 'PPO' {		// when block 2
                fineTuneRecord.E2E_Symphony_PPO_Medical_Plan__c = true;
            }
            when 'POS' {		// when block 3
                fineTuneRecord.E2E_Symphony_POS_Medical_Plan__c = true;
            }
            when 'HSA' {
                fineTuneRecord.E2E_Symphony_HSA_Medical_Plan__c = true;
            }
            when else {		  // default block, optional
                // code block 4
            }
        }

        censusRecord.Number_below_20__c = recommendationRequest.numberBelow20;
        censusRecord.Number_Between_21_30__c = recommendationRequest.numberBetween21And30;
        censusRecord.Number_between_31_40__c = recommendationRequest.numberBetween31And40;
        censusRecord.Number_between_41_50__c = recommendationRequest.numberBetween41And50;
        censusRecord.Number_between_51_60__c = recommendationRequest.numberBetween51And60;
        censusRecord.Employee_with_dependents__c = recommendationRequest.numberEK;
        censusRecord.Number_Employee_Spouse__c = recommendationRequest.numberES;
        censusRecord.Number_of_family_plans__c = recommendationRequest.numberFamilyPlans;
        censusRecord.Number_of_Female__c = recommendationRequest.numberFemale;
        censusRecord.Number_of_individual_plans__c = recommendationRequest.numberIndividualPlans;
        censusRecord.Number_of_Male__c = recommendationRequest.numberMale;
        censusRecord.Number_over_60__c = recommendationRequest.numberOver60;
        censusRecord.Number_of_Plans__c = recommendationRequest.numbOfPlans;

        currentAccount.SicDesc = recommendationRequest.sicCd + ' ' + recommendationRequest.sicDivision; 

        fineTuneRecord.E2E_Sym_Family_In_Network_Deductible_Max__c = recommendationRequest.targetDeductibleFamilyINN;
        fineTuneRecord.E2E_Sym_Fam_Out_Network_Deductible_Max__c = recommendationRequest.targetDeductibleFamilyOON;
        fineTuneRecord.E2E_Symphony_Indivdl_Ddtbl_InNet_Max__c = recommendationRequest.targetDeductibleIndividualINN;
        fineTuneRecord.E2E_Symphony_Indvl_Out_Network_Ddct_Max__c = recommendationRequest.targetDeductibleIndividualOON;
        fineTuneRecord.E2E_Sym_In_Network_Coinsurance_Maximum__c = recommendationRequest.targetINNCoinsurance * 100;
        fineTuneRecord.E2E_Sym_Out_Network_Coinsurance_Maximum__c = recommendationRequest.targetOONCoinsurance * 100;
        fineTuneRecord.E2E_Symphony_Family_Max_OoP_in_ntwrk_max__c = recommendationRequest.targetOOPMaxFamilyINN;
        fineTuneRecord.E2E_Symphony_Family_Max_OoP_ot_ntwrk_max__c = recommendationRequest.targetOOPMaxFamilyOON;
        fineTuneRecord.E2E_Symphony_Indvdl_Max_OoP_in_ntwrk_max__c = recommendationRequest.targetOOPMaxIndividualINN;
        fineTuneRecord.E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_max__c = recommendationRequest.targetOOPMaxIndividualOON;
        if(recommendationRequest.targetRxTierOneCoinsurance < 0) {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c = recommendationRequest.targetRxTierOneCoinsurance;
        } else {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c = recommendationRequest.targetRxTierOneCoinsurance * 100;
        }
        if(recommendationRequest.targetRxTierTwoCoinsurance < 0) {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c = recommendationRequest.targetRxTierTwoCoinsurance;
        } else {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c = recommendationRequest.targetRxTierTwoCoinsurance * 100;
        }    
        if(recommendationRequest.targetRxTierThreeCoinsurance < 0) {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c = recommendationRequest.targetRxTierThreeCoinsurance;  
        } else {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c = recommendationRequest.targetRxTierThreeCoinsurance * 100;  
        }
        if(recommendationRequest.targetRxTierFourCoinsurance < 0) {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c = recommendationRequest.targetRxTierFourCoinsurance;
        } else {
            fineTuneRecord.E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c = recommendationRequest.targetRxTierFourCoinsurance * 100;
        }
        fineTuneRecord.E2E_Symphony_Pharmacy_Tier_1_copay_max2__c = recommendationRequest.targetRxTierOneCopay;
        fineTuneRecord.E2E_Symphony_Pharmacy_Tier_2_copay_max__c = recommendationRequest.targetRxTierTwoCopay;
        fineTuneRecord.E2E_Symphony_Pharmacy_Tier_3_copay_max__c = recommendationRequest.targetRxTierThreeCopay;
        fineTuneRecord.E2E_Symphony_Pharmacy_Tier_4_copay_max__c = recommendationRequest.targetRxTierFourCopay;

        censusRecord.Total_Average_Age__c = recommendationRequest.totalAvgAge;
        censusRecord.Total_Dependents_Org__c = recommendationRequest.totalDpndntOrg;
        censusRecord.Total_Subscriber_Count_Org__c = recommendationRequest.totalSbscrbrCntOrg;
        
        currentAccount.BillingPostalCode = String.valueOf(recommendationRequest.zipCode);

        update censusRecord;
        update sobRecord;
        update fineTuneRecord;
        update currentAccount; 
    }
}