force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>Used in the Symphony POC and will hold the account&#39;s county.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/Census_Reimagine_POC__c.object-meta.xml
<CustomObject>
    <description>Contains information for the E2E Reimagine POC related to Group (Account) demographic data known as &quot;census&quot;.  This data can change periodically as the group profile changes</description>
    <label>Census</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Census</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Census</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Active_Member_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Member_Count__c</fullName>
    <label>Active Member Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Employee_with_dependents__c.field-meta.xml
<CustomField>
    <fullName>Employee_with_dependents__c</fullName>
    <label>Employee with dependents</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/employeeChildrenPMPM__c.field-meta.xml
<CustomField>
    <fullName>employeeChildrenPMPM__c</fullName>
    <label>Employee Children PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/employeeSpousePMPM__c.field-meta.xml
<CustomField>
    <fullName>employeeSpousePMPM__c</fullName>
    <label>Employee Spouse PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/familyPMPM__c.field-meta.xml
<CustomField>
    <fullName>familyPMPM__c</fullName>
    <label>Family PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/indvidualPMPM__c.field-meta.xml
<CustomField>
    <fullName>indvidualPMPM__c</fullName>
    <label>Individual PMPM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_below_20__c.field-meta.xml
<CustomField>
    <fullName>Number_below_20__c</fullName>
    <label>Number below 20</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_Between_21_30__c.field-meta.xml
<CustomField>
    <fullName>Number_Between_21_30__c</fullName>
    <label>Number Between 21-30</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_between_31_40__c.field-meta.xml
<CustomField>
    <fullName>Number_between_31_40__c</fullName>
    <label>Number between 31-40</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_between_41_50__c.field-meta.xml
<CustomField>
    <fullName>Number_between_41_50__c</fullName>
    <label>Number between 41-50</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_between_51_60__c.field-meta.xml
<CustomField>
    <fullName>Number_between_51_60__c</fullName>
    <label>Number between 51-60</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_Employee_Spouse__c.field-meta.xml
<CustomField>
    <fullName>Number_Employee_Spouse__c</fullName>
    <label>Number Employee + Spouse</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_family_plans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_family_plans__c</fullName>
    <label>Number of family plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_Female__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Female__c</fullName>
    <label>Number of Female</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_individual_plans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_individual_plans__c</fullName>
    <label>Number of individual plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_Male__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Male__c</fullName>
    <label>Number of Male</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_of_Plans__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Plans__c</fullName>
    <label>Number of Plans</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Number_over_60__c.field-meta.xml
<CustomField>
    <fullName>Number_over_60__c</fullName>
    <label>Number over 60</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Total_Average_Age__c.field-meta.xml
<CustomField>
    <fullName>Total_Average_Age__c</fullName>
    <label>Total Average Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Total_Dependents_Org__c.field-meta.xml
<CustomField>
    <fullName>Total_Dependents_Org__c</fullName>
    <label>Total Dependents Org</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Census_Reimagine_POC__c/fields/Total_Subscriber_Count_Org__c.field-meta.xml
<CustomField>
    <fullName>Total_Subscriber_Count_Org__c</fullName>
    <label>Total Subscriber Count Org</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/Prior_EOB_Symphony__c.object-meta.xml
<CustomObject>
    <description>Summary of Benefits</description>
    <label>SOB</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Prior EOB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SOBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SOBs</relationshipLabel>
    <relationshipName>SOBs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Coinsurance_INN__c.field-meta.xml
<CustomField>
    <fullName>Current_Coinsurance_INN__c</fullName>
    <label>Current Coinsurance INN</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Coinsurance_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_Coinsurance_OON__c</fullName>
    <label>Current Coinsurance OON</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Family_Deductible_In_Network__c.field-meta.xml
<CustomField>
    <fullName>Current_Family_Deductible_In_Network__c</fullName>
    <label>Current Family Deductible In Network</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Family_Deductible_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_Family_Deductible_OON__c</fullName>
    <label>Current Family Deductible OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Individual_Deductible_In_Network__c.field-meta.xml
<CustomField>
    <fullName>Current_Individual_Deductible_In_Network__c</fullName>
    <label>Current Individual Deductible In Network</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Individual_Deductible_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_Individual_Deductible_OON__c</fullName>
    <label>Current Individual Deductible OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Family_INN__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Family_INN__c</fullName>
    <label>Current OOP max Family INN</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Family_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Family_OON__c</fullName>
    <label>Current OOP max Family OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Individual_INN__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Individual_INN__c</fullName>
    <label>Current OOP max Individual INN</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_OOP_max_Individual_OON__c.field-meta.xml
<CustomField>
    <fullName>Current_OOP_max_Individual_OON__c</fullName>
    <label>Current OOP max Individual OON</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Four_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Four_Coinsurance__c</fullName>
    <label>Current Rx Tier Four Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Four_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Four_Copay__c</fullName>
    <label>Current Rx Tier Four Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_One_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_One_Coinsurance__c</fullName>
    <label>Current Rx Tier One Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_One_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_One_Copay__c</fullName>
    <label>Current Rx Tier One Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Three_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Three_Coinsurance__c</fullName>
    <label>Current Rx Tier Three Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Three_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Three_Copay__c</fullName>
    <label>Current Rx Tier Three Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Two_Coinsurance__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Two_Coinsurance__c</fullName>
    <label>Current Rx Tier Two Coinsurance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Prior_EOB_Symphony__c/fields/Current_Rx_Tier_Two_Copay__c.field-meta.xml
<CustomField>
    <fullName>Current_Rx_Tier_Two_Copay__c</fullName>
    <label>Current Rx Tier Two Copay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Symphony_Status__c.field-meta.xml
<CustomField>
    <fullName>Symphony_Status__c</fullName>
    <description>Used in the symphony POC and stores the pizza tracker status.</description>
    <label>Symphony Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Profile</fullName>
            </value>
            <value>
                <fullName>Get Recommendation</fullName>
            </value>
            <value>
                <fullName>Get Rate</fullName>
            </value>
            <value>
                <fullName>Plan Selection</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Customer Setup</fullName>
            </value>
            <value>
                <fullName>Access to Care</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/symphonyCoLo3Demo.cls
public with sharing class symphonyCoLo3Demo {
    @InvocableMethod(label='Call Recommendation')
    public static List<string> sendRecommendation(List <Id> quoteId) {
        Quote theQuote = [SELECT Id, Account.Id, Opportunity.Id, Symphony_Status__c 
        FROM Quote 
        WHERE id = :quoteId[0] LIMIT 1];
        Account theAccount = [SELECT Id, Name, County__c, SicDesc, BillingPostalCode 
        FROM Account 
        WHERE id = :theQuote.Account.Id LIMIT 1];
        Census_Reimagine_POC__c theCensus = [Select Id, Active_Member_Count__c, Number_below_20__c, Number_Between_21_30__c,
        Number_between_31_40__c, Number_between_41_50__c, Number_between_51_60__c, Number_Employee_Spouse__c, Number_of_family_plans__c,
        Number_of_Female__c, Number_of_individual_plans__c, Number_of_Male__c, Number_over_60__c, employeeChildrenPMPM__c,
        employeeSpousePMPM__c, familyPMPM__c , indvidualPMPM__c, Employee_with_dependents__c, Number_of_Plans__c, State__c,
        Total_Average_Age__c, Total_Dependents_Org__c, Total_Subscriber_Count_Org__c
        FROM Census_Reimagine_POC__c
        WHERE Account__c = :theAccount.id LIMIT 1];
        Prior_EOB_Symphony__c theEOB = [SELECT Id, Current_Coinsurance_INN__c, Current_Coinsurance_OON__c,
        Current_Family_Deductible_In_Network__c, Current_Family_Deductible_OON__c, Current_Individual_Deductible_In_Network__c,
        Current_Individual_Deductible_OON__c, Current_OOP_max_Family_INN__c, Current_OOP_max_Family_OON__c,
        Current_OOP_max_Individual_INN__c,Current_Rx_Tier_Four_Coinsurance__c, Current_Rx_Tier_Four_Copay__c,
        Current_Rx_Tier_One_Coinsurance__c, Current_Rx_Tier_One_Copay__c, Current_Rx_Tier_Three_Coinsurance__c,
        Current_Rx_Tier_Three_Copay__c, Current_Rx_Tier_Two_Coinsurance__c, Current_Rx_Tier_Two_Copay__c,
        Current_OOP_max_Individual_OON__c
        FROM Prior_EOB_Symphony__c
        WHERE Account__c = :theAccount.id LIMIT 1];
        E2E_Symphony_Fine_Tune_Recommendation__c theFT = [SELECT Id, E2E_Sym_Family_In_Network_Deductible_Max__c,
        E2E_Sym_Fam_Out_Network_Deductible_Max__c, E2E_Symphony_Indivdl_Ddtbl_InNet_Max__c,
        E2E_Symphony_Indvl_Out_Network_Ddct_Max__c, E2E_Sym_Out_Network_Coinsurance_Maximum__c,
        E2E_Sym_In_Network_Coinsurance_Maximum__c, E2E_Symphony_Family_Max_OoP_in_ntwrk_max__c,
        E2E_Symphony_Family_Max_OoP_ot_ntwrk_max__c, E2E_Symphony_Indvdl_Max_OoP_in_ntwrk_max__c,
        E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_max__c, E2E_Symphony_HMO_Medical_Plan__c,
        E2E_Symphony_HSA_Medical_Plan__c, E2E_Symphony_POS_Medical_Plan__c, E2E_Symphony_PPO_Medical_Plan__c,
        E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_1_copay_max2__c,
        E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_2_copay_max__c,
        E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_3_copay_max__c,
        E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_4_copay_max__c        
        FROM E2E_Symphony_Fine_Tune_Recommendation__c
        WHERE E2E_Symphony_Account__c = :theAccount.Id];
        AnthemAPI.RecommendationRequest recommendationRequest = new AnthemAPI.RecommendationRequest();
        recommendationRequest.activeMemberCount = integer.valueOf(theCensus.Active_Member_Count__c);
        recommendationRequest.county = theAccount.County__c;
        recommendationRequest.currentCoinsuranceINN = theEOB.Current_Coinsurance_INN__c / 100;
        recommendationRequest.currentCoinsuranceOON = theEOB.Current_Coinsurance_OON__c / 100;
        recommendationRequest.currentFamilyDeductibleINN = integer.valueOf(theEOB.Current_Family_Deductible_In_Network__c);
        recommendationRequest.currentFamilyDeductibleOON = integer.valueOf(theEOB.Current_Family_Deductible_OON__c);
        recommendationRequest.currentIndividualDeductibleINN = integer.valueOf(theEOB.Current_Individual_Deductible_In_Network__c);
        recommendationRequest.currentIndividualDeductibleOON = integer.valueOf(theEOB.Current_Individual_Deductible_OON__c);
        recommendationRequest.currentOOPmaxFamilyINN = integer.valueof(theEOB.Current_OOP_max_Family_INN__c);
        recommendationRequest.currentOOPmaxFamilyOON = integer.valueof(theEOB.Current_OOP_max_Family_OON__c);
        recommendationRequest.currentOOPmaxIndividualINN = integer.valueof(theEOB.Current_OOP_max_Individual_INN__c);
        recommendationRequest.currentOOPmaxIndividualOON = integer.valueof(theEOB.Current_OOP_max_Individual_OON__c);
        recommendationRequest.currentRxTierFourCoinsurance = theEOB.Current_Rx_Tier_Four_Coinsurance__c / 100;
        recommendationRequest.currentRxTierFourCopay = integer.valueof(theEOB.Current_Rx_Tier_Four_Copay__c / 100);
        recommendationRequest.currentRxTierOneCoinsurance = theEOB.Current_Rx_Tier_One_Coinsurance__c / 100;
        recommendationRequest.currentRxTierOneCopay = integer.valueOf(theEOB.Current_Rx_Tier_One_Copay__c);
        recommendationRequest.currentRxTierThreeCoinsurance = theEOB.Current_Rx_Tier_Three_Coinsurance__c / 100;
        recommendationRequest.currentRxTierThreeCopay = integer.valueOf(theEOB.Current_Rx_Tier_Three_Copay__c);
        recommendationRequest.currentRxTierTwoCoinsurance = theEOB.Current_Rx_Tier_Two_Coinsurance__c / 100;
        recommendationRequest.currentRxTierTwoCopay = integer.valueOf(theEOB.Current_Rx_Tier_Two_Copay__c);
        recommendationRequest.effectiveDt = '01/01/2020';
        recommendationRequest.employeeChildrenPMPM = theCensus.employeeChildrenPMPM__c;
        recommendationRequest.employeeSpousePMPM = theCensus.employeeSpousePMPM__c;
        recommendationRequest.familyPMPM = theCensus.familyPMPM__c;
        recommendationRequest.indvidualPMPM = theCensus.indvidualPMPM__c;
        if(theFT.E2E_Symphony_HMO_Medical_Plan__c) {
            recommendationRequest.memberSelectionCategory = 'HMO';
        }
        if(theFT.E2E_Symphony_PPO_Medical_Plan__c) {
            recommendationRequest.memberSelectionCategory = 'PPO';
        }
        if(theFT.E2E_Symphony_POS_Medical_Plan__c) {
            recommendationRequest.memberSelectionCategory = 'POS';
        }
        if(theFT.E2E_Symphony_HSA_Medical_Plan__c) {
            recommendationRequest.memberSelectionCategory = 'HSA';
        }
        recommendationRequest.numberBelow20 = integer.valueOf(theCensus.Number_below_20__c);
        recommendationRequest.numberBetween21And30 = integer.valueOf(theCensus.Number_Between_21_30__c);
        recommendationRequest.numberBetween31And40 = integer.valueOf(theCensus.Number_between_31_40__c);
        recommendationRequest.numberBetween41And50 = integer.valueOf(theCensus.Number_between_41_50__c);
        recommendationRequest.numberBetween51And60 = integer.valueOf(theCensus.Number_between_51_60__c);
        recommendationRequest.numberEK = integer.ValueOf(theCensus.Employee_with_dependents__c);
        recommendationRequest.numberES = integer.valueOf(theCensus.Number_Employee_Spouse__c);
        recommendationRequest.numberFamilyPlans = integer.valueOf(theCensus.Number_of_family_plans__c);
        recommendationRequest.numberFemale = integer.valueOf(theCensus.Number_of_Female__c);
        recommendationRequest.numberIndividualPlans = integer.valueOf(theCensus.Number_of_individual_plans__c);
        recommendationRequest.numberMale = integer.valueOf(theCensus.Number_of_Male__c);
        recommendationRequest.numberOver60 = integer.valueOf(theCensus.Number_over_60__c);
        recommendationRequest.numbOfPlans = integer.valueOf(theCensus.Number_of_Plans__c);
        //recommendationRequest.sicCd = integer.ValueOf(theAccount.SicDesc.SubStringBefore(' '));
        //recommendationRequest.sicDivision = theAccount.SicDesc.SubStringAfter(' ');
        recommendationRequest.sicCd = 8211;
        recommendationRequest.sicDivision = 'Services';

        recommendationRequest.stateCode = theCensus.State__c;
        recommendationRequest.targetDeductibleFamilyINN = integer.ValueOf(theFT.E2E_Sym_Family_In_Network_Deductible_Max__c);
        recommendationRequest.targetDeductibleFamilyOON = integer.ValueOf(theFT.E2E_Sym_Fam_Out_Network_Deductible_Max__c);
        recommendationRequest.targetDeductibleIndividualINN = integer.ValueOf(theFT.E2E_Symphony_Indivdl_Ddtbl_InNet_Max__c);
        recommendationRequest.targetDeductibleIndividualOON = integer.ValueOf(theFT.E2E_Symphony_Indvl_Out_Network_Ddct_Max__c);
        recommendationRequest.targetINNCoinsurance = theFT.E2E_Sym_In_Network_Coinsurance_Maximum__c / 100;
        recommendationRequest.targetOONCoinsurance = theFT.E2E_Sym_Out_Network_Coinsurance_Maximum__c / 100;
        recommendationRequest.targetOOPMaxFamilyINN = integer.ValueOf(theFT.E2E_Symphony_Family_Max_OoP_in_ntwrk_max__c);
        recommendationRequest.targetOOPMaxFamilyOON = integer.ValueOf(theFT.E2E_Symphony_Family_Max_OoP_ot_ntwrk_max__c);
        recommendationRequest.targetOOPMaxIndividualINN = integer.ValueOf(theFT.E2E_Symphony_Indvdl_Max_OoP_in_ntwrk_max__c);
        recommendationRequest.targetOOPMaxIndividualOON = integer.ValueOf(theFT.E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_max__c);
        recommendationRequest.targetRxTierFourCoinsurance = theFt.E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c / 100;
        recommendationRequest.targetRxTierFourCopay = integer.valueOf(theFt.E2E_Symphony_Pharmacy_Tier_4_copay_max__c);
        recommendationRequest.targetRxTierOneCoinsurance = theFt.E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c / 100;
        recommendationRequest.targetRxTierOneCopay = integer.valueOf(theFt.E2E_Symphony_Pharmacy_Tier_1_copay_max2__c);
        recommendationRequest.targetRxTierThreeCoinsurance = theFt.E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c / 100;
        recommendationRequest.targetRxTierThreeCopay = integer.valueOf(theFt.E2E_Symphony_Pharmacy_Tier_3_copay_max__c);
        recommendationRequest.targetRxTierTwoCoinsurance = theFt.E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c / 100;
        recommendationRequest.targetRxTierTwoCopay = integer.valueOf(theFt.E2E_Symphony_Pharmacy_Tier_2_copay_max__c);
        recommendationRequest.totalAvgAge = integer.valueOf(theCensus.Total_Average_Age__c);
        recommendationRequest.totalDpndntOrg = integer.valueOf(theCensus.Total_Dependents_Org__c);
        recommendationRequest.totalSbscrbrCntOrg = integer.valueOf(theCensus.Total_Subscriber_Count_Org__c);
        recommendationRequest.zipCode = integer.valueOf(theAccount.BillingPostalCode);
        //recommendationRequest.zipCode = 45226;
        system.debug(recommendationRequest);
        AnthemAPI.RecommendationResponse recommendationResponse = AnthemAPI.getRecommendations(recommendationRequest);

        List<AnthemAPI.Plan> thePopularPlans = recommendationResponse.popularPlan;
        List<AnthemAPI.Plan> theRecommendedPlans = recommendationResponse.recommendedPlans;

        String temp = '';
        List<Product2> returnedProducts = new List<Product2>();
        List<String> product2Ids = new List<String>();

        List<String> theResult = new List<String>();
        if(thePopularPlans == null && theRecommendedPlans == null) {
            //theResult.add('No matching plans');
            theResult.add(recommendationResponse.toString());
        } else {
            List<QuoteLineItem> delQLIs = [SELECT Id FROM QuoteLineItem WHERE QuoteId=:theQuote.Id];
            delete(delQLIs);

            for(AnthemApi.Plan p: thePopularPlans) {
                product2Ids.add(p.contractCd);
            }
            for(AnthemApi.Plan p: theRecommendedPlans) {
                product2Ids.add(p.contractCd);
            }
            returnedProducts = [SELECT Id, Name, Contract_Code__c FROM Product2 WHERE Contract_Code__c IN :product2Ids];

            List<QuoteLineItem> newQLIs = new List<QuoteLineItem>();

           for(Product2 p : returnedProducts) {
                QuoteLineItem q = new QuoteLineItem(
                    PricebookEntryId='01u1K00000bi4tcQAA', Product2Id=p.Id, Opportunity__c=theQuote.Opportunity.Id,
                    ProductStage__c='In Progress', Quantity=1, QuoteId=theQuote.Id, UnitPrice=950
                );
                newQLIs.add(q);
            }

            insert(newQLIs);
            theQuote.Symphony_Status__c = 'Get Rate';
            update(theQuote);
            theResult.add(recommendationResponse.toString());
        }
        
        //List<String> theResult = new List<String>();
        return theResult;
    }
}