force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/E2E_Symphony_Fine_Tune_Recommendation__c.object-meta.xml
<CustomObject>
    <label>Fine Tune Recommendations</label>
    <nameField>
        <displayFormat>FTR-{00000}</displayFormat>
        <label>Fine Tune Recommendation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fine Tune Recommendations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Fam_Out_Network_Deductible_Max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Fam_Out_Network_Deductible_Max__c</fullName>
    <label>Family deductible out of network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Fam_Out_Network_Deductible_Min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Fam_Out_Network_Deductible_Min__c</fullName>
    <label>Family deductible out of network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Family_In_Network_Deductible_Max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Family_In_Network_Deductible_Max__c</fullName>
    <label>Family deductible in network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Family_In_Network_Deductible_Min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Family_In_Network_Deductible_Min__c</fullName>
    <label>Family deductible in network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_In_Network_Coinsurance_Maximum__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_In_Network_Coinsurance_Maximum__c</fullName>
    <label>In network Coinsurance max</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_In_Network_Coinsurance_Minimum__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_In_Network_Coinsurance_Minimum__c</fullName>
    <label>In network Coinsurance min</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Out_Network_Coinsurance_Maximum__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Out_Network_Coinsurance_Maximum__c</fullName>
    <label>Out-of-Network Coinsurance Maximum</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Sym_Out_Network_Coinsurance_Minimum__c.field-meta.xml
<CustomField>
    <fullName>E2E_Sym_Out_Network_Coinsurance_Minimum__c</fullName>
    <label>Out-of-Network Coinsurance Minimum</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Account__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fine Tune Recommendations</relationshipLabel>
    <relationshipName>Fine_Tune_Recommendations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Data_sets_visible_to_client__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Data_sets_visible_to_client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow client to view data sets chosen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Family_Max_Oo_in_ntwrk_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Family_Max_Oo_in_ntwrk_min__c</fullName>
    <label>Family Max Out-of-Pocket in network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Family_Max_OoP_in_ntwrk_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Family_Max_OoP_in_ntwrk_max__c</fullName>
    <label>Family Max Out-of-Pocket in network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Family_Max_OoP_ot_ntwrk_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Family_Max_OoP_ot_ntwrk_max__c</fullName>
    <label>Family Max Out-of-Pocket out network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Family_Max_OoP_ot_ntwrk_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Family_Max_OoP_ot_ntwrk_min__c</fullName>
    <label>Family Max Out-of-Pocket out network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_HMO_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_HMO_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HMO Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_HSA_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_HSA_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HSA Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Indivdl_Ddtbl_InNet_Max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Indivdl_Ddtbl_InNet_Max__c</fullName>
    <label>Individual deductible in network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Individual_Max_OoP_in_ntwrk__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Individual_Max_OoP_in_ntwrk__c</fullName>
    <label>Indvdl Max Out-of-Pocket in network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Indvdl_In_Ntwk_Deduct_Min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Indvdl_In_Ntwk_Deduct_Min__c</fullName>
    <label>Individual deductible in network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Indvdl_Max_OoP_in_ntwrk_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Indvdl_Max_OoP_in_ntwrk_max__c</fullName>
    <label>Indvdl Max Out-of-Pocket in network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_max__c</fullName>
    <label>Indvdl Max Out-of-Pocket out network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_min__c</fullName>
    <label>Indvdl Max Out-of-Pocket out network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Indvl_Out_Network_Ddct_Max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Indvl_Out_Network_Ddct_Max__c</fullName>
    <label>Individual deductible out of network max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Invdl_Out_Ntwk_Dtbl_Min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Invdl_Out_Ntwk_Dtbl_Min__c</fullName>
    <label>Individual deductible out of network min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c</fullName>
    <label>Pharmacy Tier 1 coinsurance max</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_1_coinsur_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_1_coinsur_min__c</fullName>
    <label>Pharmacy Tier 1 coinsurance min</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_1_copay_max2__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_1_copay_max2__c</fullName>
    <label>Pharmacy Tier 1 copay max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_1_copay_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_1_copay_min__c</fullName>
    <label>Pharmacy Tier 1 copay min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c</fullName>
    <label>Pharmacy Tier 2 coinsurance max</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_2_coinsur_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_2_coinsur_min__c</fullName>
    <label>Pharmacy Tier 2 coinsurance min</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_2_copay_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_2_copay_max__c</fullName>
    <label>Pharmacy Tier 2 copay max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_2_copay_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_2_copay_min__c</fullName>
    <label>Pharmacy Tier 2 copay min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c</fullName>
    <label>Pharmacy Tier 3 coinsurance max</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_3_coinsur_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_3_coinsur_min__c</fullName>
    <label>Pharmacy Tier 3 coinsurance min</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_3_copay_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_3_copay_max__c</fullName>
    <label>Pharmacy Tier 3 copay max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_3_copay_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_3_copay_min__c</fullName>
    <label>Pharmacy Tier 3 copay min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c</fullName>
    <label>Pharmacy Tier 4 coinsurance max</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_4_Coinsur_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_4_Coinsur_min__c</fullName>
    <label>Pharmacy Tier 4 Coinsurance min</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_4_copay_max__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_4_copay_max__c</fullName>
    <label>Pharmacy Tier 4 copay max</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_Pharmacy_Tier_4_copay_min__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_Pharmacy_Tier_4_copay_min__c</fullName>
    <label>Pharmacy Tier 4 copay min</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_POS_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_POS_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POS Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/E2E_Symphony_Fine_Tune_Recommendation__c/fields/E2E_Symphony_PPO_Medical_Plan__c.field-meta.xml
<CustomField>
    <fullName>E2E_Symphony_PPO_Medical_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PPO Medical Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/symphonyGetFineTuneRecommendations.cls
public with sharing class symphonyGetFineTuneRecommendations {
    @AuraEnabled(cacheable=true)
    public static E2E_Symphony_Fine_Tune_Recommendation__c symphonyGetFineTuneRecommendations(Id recordId) {
        E2E_Symphony_Fine_Tune_Recommendation__c fineTuneRecord = [SELECT Id, E2E_Sym_Family_In_Network_Deductible_Max__c,
        E2E_Sym_Family_In_Network_Deductible_Min__c,E2E_Symphony_PPO_Medical_Plan__c,E2E_Symphony_HMO_Medical_Plan__c,
        E2E_Symphony_POS_Medical_Plan__c, E2E_Symphony_HSA_Medical_Plan__c,E2E_Sym_Fam_Out_Network_Deductible_Min__c,
        E2E_Sym_Fam_Out_Network_Deductible_Max__c,E2E_Symphony_Invdl_Out_Ntwk_Dtbl_Min__c, E2E_Symphony_Indvdl_In_Ntwk_Deduct_Min__c,
        E2E_Symphony_Indvl_Out_Network_Ddct_Max__c, E2E_Symphony_Indivdl_Ddtbl_InNet_Max__c, E2E_Symphony_Indvdl_Max_OoP_in_ntwrk_max__c,
        E2E_Symphony_Individual_Max_OoP_in_ntwrk__c, E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_min__c, E2E_Symphony_Indvdl_Max_OoP_ot_ntwrk_max__c,
        E2E_Symphony_Family_Max_OoP_in_ntwrk_max__c, E2E_Symphony_Family_Max_Oo_in_ntwrk_min__c, E2E_Symphony_Family_Max_OoP_ot_ntwrk_min__c,
        E2E_Symphony_Family_Max_OoP_ot_ntwrk_max__c, E2E_Sym_In_Network_Coinsurance_Maximum__c,E2E_Sym_In_Network_Coinsurance_Minimum__c,
        E2E_Sym_Out_Network_Coinsurance_Maximum__c, E2E_Sym_Out_Network_Coinsurance_Minimum__c, E2E_Symphony_Pharmacy_Tier_1_coinsur_min__c,
        E2E_Symphony_Pharmacy_Tier_1_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_2_coinsur_min__c, E2E_Symphony_Pharmacy_Tier_2_coinsur_max__c,
        E2E_Symphony_Pharmacy_Tier_3_coinsur_min__c, E2E_Symphony_Pharmacy_Tier_3_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_4_Coinsur_min__c,
        E2E_Symphony_Pharmacy_Tier_4_coinsur_max__c, E2E_Symphony_Pharmacy_Tier_1_copay_min__c, E2E_Symphony_Pharmacy_Tier_1_copay_max2__c,
        E2E_Symphony_Pharmacy_Tier_2_copay_min__c, E2E_Symphony_Pharmacy_Tier_2_copay_max__c, E2E_Symphony_Pharmacy_Tier_3_copay_min__c,
        E2E_Symphony_Pharmacy_Tier_3_copay_max__c, E2E_Symphony_Pharmacy_Tier_4_copay_min__c, E2E_Symphony_Pharmacy_Tier_4_copay_max__c,
        E2E_Symphony_Data_sets_visible_to_client__c
        FROM E2E_Symphony_Fine_Tune_Recommendation__c
        WHERE E2E_Symphony_Account__c = :recordId];

        return fineTuneRecord;
    }

    @AuraEnabled()
    public static String symphonySaveFineTuneRecommendations(Id recordId, Boolean PPOCheck, Boolean HMOCheck, Boolean POSCheck, Boolean HSACheck) {

        E2E_Symphony_Fine_Tune_Recommendation__c recommendationRecord = [Select Id, E2E_Symphony_Account__c
        FROM E2E_Symphony_Fine_Tune_Recommendation__c 
        WHERE E2E_Symphony_Account__c = :recordId];

        String returnMessage = 'Success';

        recommendationRecord.E2E_Symphony_PPO_Medical_Plan__c = PPOCheck;
        recommendationRecord.E2E_Symphony_HMO_Medical_Plan__c = HMOCheck;
        recommendationRecord.E2E_Symphony_POS_Medical_Plan__c = POSCheck;
        recommendationRecord.E2E_Symphony_HSA_Medical_Plan__c = HSACheck;

        try {
            update recommendationRecord;
        } catch(DmlException e) {
            returnMessage = e.getMessage();
        }
        system.debug(returnMessage);
        return returnMessage;
    }
}